### ISSUE TITLE
Could I  use other autoform hook method like "onSuccess"...

### ISSUE THREAD

**Issue by yuomtheara** [Planifica/meteor-wizard#10]
Could I  use other autoform hook method like `onSuccess`, `berforeInsert`...
Please help me.

**Comment by yuomtheara** [comment]
I want to use `formToDoc` hook, because I need customers other fields before check validation.

**Comment by barboni** [comment]
you can now call AutoForm.addHooks with your step ids and the needed hooks.

**Comment by thearabbit** [comment]
I tried, but don't work.

**Comment by barboni** [comment]
make sure that you use the latest package version, 0.0.7

**Comment by thearabbit** [comment]
Yes v0.0.7, It show debug `AutoForm is not defined`

``` js
AutoForm.hooks({
    setupStepTow: {
        onSubmit: function (insertDoc, updateDoc, currentDoc) {
            this.done(); 
        }
        onSuccess: function (formType, result) {
            alert('Success');
        }
    }
});
```

**Comment by barboni** [comment]
you still need to add the autoform package to your project if you want to use it.

**Comment by thearabbit** [comment]
Yes I want to use `autoform hook` with `wizard`.
But  don't work.

**Comment by thearabbit** [comment]
OK, now I add `autoform` package, and add `onSuccess` hook like

``` js
Template.setupWizard.steps = function() {
  return [{
    id: 'stepOne',
    ...
  }, {
    id: 'stepTwo',
    ...
    onSubmit: function(data, mergedData) { 
      var self = this;
      Accounts.createUser(mergedData, function(err) {
        if(!err) self.done();
      });
    }
  }]
}

/**
 * Hook
 */
AutoForm.hooks({
    stepTwo: {
        onSuccess: function (formType, result) {
            alert('Success');
        }
    }
});
```

But don't work.

**Comment by thearabbit** [comment]
I think that, problem with `this` reference of `autoform`.
