### ISSUE TITLE
Manually moving to the next step

### ISSUE THREAD

**Issue by eventrio** [Planifica/meteor-wizard#4]
So I was really liking your package before the last update, it was easy to use, and fit my use case exactly. I need to be able to manually move to the next step in the process after doing some processing on the data entered. I was able to do that using:

    wizard.next() 

inside the onSubmit callback for each step, now it seems that the wizard parameter has been removed and replaced with the mergedData parameter, and furthermore the next method has been removed from the wizard all together.

How can I manually continue to the next step in the wizard now?

**Comment by eventrio** [comment]
Well I figured out that you basically force me to set it up with routes and redirects, I guess that is okay for me because I was already using iron:router, but it does limit the usability for people who are using a different routing package.

**Comment by eventrio** [comment]
Okay so I thought I had it figured out but I do not, I can not get it to move past the first step. 

Here is how I have it set up:
 the route:
  
    Router.route("/account-setup/:step", {
        name:"accountSetup",
        layoutTemplate:"homeLayout",
        data:function(){
    
        return {data:Meteor.user().profile }
      }
    });

Now the wizard definition:

    {{> wizard id="account-wizard" steps=steps stepsTemplate="steps" route="accountSetup" clearOnDestroy=true}}

and finally the steps template:


    Template.accountSetupWizard.helpers({
	steps: function() {
    	return [{
	      		id: 'personal',
	      		title: 'Personal Profile',
	      		template: 'underwritingForm',
	      		formId: 'underwritingForm',
	      		onSubmit: function(data, merged) { //data is current step data
	      			
	      			Session.set("inSetup", true);
	        		var self = this; // self now references the AutoForm instance
					...cut for brevity
							Router.go("/account-setup/company");
							
						}
					});
					
				}
	    	},{
	      		id: 'company',
	      		title: 'Company Profile',
	      		template: 'companiesForm',
	      		formId: 'companiesForm',
	      		onSubmit: function(data, wizard) { //data is current step data
	        		var self = this; // self now references the AutoForm instance
                                .... brevity
	       			Router.go("/account-setup/images");	
	        	
	      	}

    	];
  	}
    });

Can you give me some help?

**Comment by PhilippSpo** [comment]
Yeah there was a bug that should now be fixed. You can use this.next() in your onSubmit handler again.
Sorry for that!
[bugfix](https://github.com/Planifica/meteor-wizard/commit/2361fce42979714d23a184de758e6fc97ab4118e)

**Comment by eventrio** [comment]
Awesome thanks, that seems to have taken care of it.
