### ISSUE TITLE
amplify stored objects not compatible with u2622:persistent-session

### ISSUE THREAD

**Issue by tcastelli** [Planifica/meteor-wizard#8]
Since version 0.3 of persistent-session, I get errors when trying to persist the steps with amplify since it says it's not an EJSONable object. Any chance of changing this part to make it compatible with persistent-session?

Thanks!

**Comment by PhilippSpo** [comment]
We removed the dependency to amplify and now also use the persistent-session package. So I think you should not get any more errors now.
